<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table): void {
            // Products use a ULID identity generated by the domain aggregate.
            $table->ulid('id')->primary();
            // Workspaces/categories keep integer identities (see their migrations).
            $table->foreignId('workspace_id')->constrained('workspaces')->cascadeOnDelete();
            $table->foreignId('category_id')->nullable()->constrained('categories')->nullOnDelete();
            $table->string('name', 200);
            $table->string('description')->nullable();
            $table->string('sku', 30)->comment('Format: CATG-001. Unique per workspace.');
            $table->string('barcode', 100)->nullable()->comment('EAN-13, QR or custom barcode');
            $table->unsignedInteger('current_stock')->default(0);
            $table->unsignedInteger('minimum_stock')->default(0)->comment('Alert threshold');
            $table->unsignedBigInteger('cost_price_cents')->default(0)->comment('Stored in cents to avoid float imprecision');
            $table->unsignedBigInteger('sale_price_cents')->default(0);
            $table->string('unit', 10)->default('un')->comment('un, kg, l, cx, pc');
            $table->string('status', 20)->default('active');
            $table->string('qr_code_path')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->unique(['workspace_id', 'sku']);
            $table->index(['workspace_id', 'status']);
            $table->index(['workspace_id', 'current_stock']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};
