<?php

declare(strict_types=1);

namespace Stockr\Infrastructure\Persistence\Eloquent\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Stockr\Domain\Inventory\ValueObjects\ProductStatus;

/**
 * Pure persistence mapping for the `products` table — no business logic, no
 * domain methods, only column mapping, casts and relationships. Uses a string
 * (ULID) primary key generated by the domain aggregate.
 *
 * @property string $id
 * @property int $workspace_id
 * @property int|null $category_id
 * @property string $name
 * @property string|null $description
 * @property string $sku
 * @property string|null $barcode
 * @property int $current_stock
 * @property int $minimum_stock
 * @property int $cost_price_cents
 * @property int $sale_price_cents
 * @property string $unit
 * @property ProductStatus $status
 * @property string|null $qr_code_path
 */
final class ProductModel extends Model
{
    use SoftDeletes;

    protected $table = 'products';

    protected $keyType = 'string';

    public $incrementing = false;

    protected $fillable = [
        'id',
        'workspace_id',
        'category_id',
        'name',
        'description',
        'sku',
        'barcode',
        'current_stock',
        'minimum_stock',
        'cost_price_cents',
        'sale_price_cents',
        'unit',
        'status',
        'qr_code_path',
    ];

    protected function casts(): array
    {
        return [
            'id' => 'string',
            'workspace_id' => 'integer',
            'category_id' => 'integer',
            'current_stock' => 'integer',
            'minimum_stock' => 'integer',
            'cost_price_cents' => 'integer',
            'sale_price_cents' => 'integer',
            'status' => ProductStatus::class,
        ];
    }

    public function workspace(): BelongsTo
    {
        return $this->belongsTo(WorkspaceModel::class, 'workspace_id');
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(CategoryModel::class, 'category_id');
    }

    public function movements(): HasMany
    {
        return $this->hasMany(MovementModel::class, 'product_id');
    }

    /**
     * Used by the `filter[low_stock]=true` query parameter.
     *
     * @param  Builder<ProductModel>  $query
     */
    public function scopeLowStock(Builder $query, bool $only = true): void
    {
        if ($only) {
            $query->whereColumn('current_stock', '<=', 'minimum_stock');
        }
    }
}
